package types

const (
	BALANCE_NO_ENOUGH_MONEY          = "HISOBDA YETARLIK MABLAG' MAVJUD EMAS"
	DEBTOR_NO_ENOUGH_MONEY           = "QARZDORDA YETARLIK MABLAG' MAVJUD EMAS"
	BALANCE_CURRENCY_NOT_FOUND       = "BUNDAY VALYUTALIK HISOB MAVJUD EMAS"
	SERVICE_FEE_REQUIRED_AT_COMPLETE = "XIZMAT HAQI KIRITILMAGAN"

	// 3 bosqichli tranzaksiya oqimi (business_settings.transaction_flow = 2).
	TRANSACTION_ACCEPT_DISABLED  = "QABUL QILISH BOSQICHI SOZLAMALARDA YOQILMAGAN"
	TRANSACTION_ALREADY_ACCEPTED = "BUYURTMA ALLAQACHON QABUL QILINGAN"
	TRANSACTION_NOT_ACCEPTED     = "BUYURTMA HALI QABUL QILINMAGAN"
)
