package types

const (
	BALANCE_NO_ENOUGH_MONEY          = "HISOBDA YETARLIK MABLAG' MAVJUD EMAS"
	DEBTOR_NO_ENOUGH_MONEY           = "QARZDORDA YETARLIK MABLAG' MAVJUD EMAS"
	BALANCE_CURRENCY_NOT_FOUND       = "BUNDAY VALYUTALIK HISOB MAVJUD EMAS"
	SERVICE_FEE_REQUIRED_AT_COMPLETE = "XIZMAT HAQI KIRITILMAGAN"
)
